/*
 * This file is generated by jOOQ.
 */
package domain.db;


import domain.db.tables.FlywaySchemaHistory;
import domain.db.tables.Tasks;
import domain.db.tables.TasksProperties;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.tasks</code>.
     */
    public static final Tasks TASKS = Tasks.TASKS;

    /**
     * The table <code>public.tasks_properties</code>.
     */
    public static final TasksProperties TASKS_PROPERTIES = TasksProperties.TASKS_PROPERTIES;
}
