/*
 * This file is generated by jOOQ.
 */
package domain.db.enums;


import domain.db.Public;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum Taskstatusenum implements EnumType {

    SCHEDULED("SCHEDULED"),

    COMPLETED("COMPLETED"),

    FAILED("FAILED");

    private final String literal;

    private Taskstatusenum(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public String getName() {
        return "taskstatusenum";
    }

    @Override
    public String getLiteral() {
        return literal;
    }
}
